// Book data
const bookData = [
  {
    id: 1,
    title: "Rewire Your Anxious Brain",
    author: "Nick Trenton",
    category: "psychology",
    cover: "https://m.media-amazon.com/images/I/71iyoGwTfBL._AC_UL320_.jpg",
    rating: 4.5,
    pages: 320,
    content: "<h3>Chapter 1: The Characters of the Story</h3><p>To observe your mind in automatic mode, glance at the image below...</p>",
  },
  {
    id: 2,
    title: "Drak Physicology and Manipulation",
    author: "William Cooper",
    category: "psychology",
    cover: "https://m.media-amazon.com/images/I/61X8IJmUqiL._AC_UL320_.jpg",
    rating: 4.4,
    pages: 371,
    content: "<h3>Chapter 1: The Habit Loop</h3><p>Habits, scientists say, emerge because the brain is constantly looking for ways to save effort...</p>",
  },
  {
    id: 3,
    title: "As The Man Thinketh",
    author: "James Allen",
    category: "psychology",
    cover: "https://m.media-amazon.com/images/I/61eQzgBwEoL._AC_UL320_.jpg",
    rating: 4.7,
    pages: 320,
    content: "<h3>Chapter 1: The Surprising Power of Tiny Habits</h3><p>Success is the product of daily habits—not once-in-a-lifetime transformations...</p>",
  },
  {
    id: 4,
    title: "The Power Of Your subconscious Mind",
    author: "Joseph Murphy",
    category: "psychology",
    cover: "https://m.media-amazon.com/images/I/71sBtM3Yi5L._AC_SR405%2C405_.jpg",
    rating: 4.8,
    pages: 464,
    content: "<h3>Chapter 1: Lessons from Vietnam Veterans</h3><p>The first time I walked into the Veterans Administration Hospital in Boston in 1978...</p>",
  },
  {
    id: 5,
    title: "Energy Physicology Using Light & Color  ",
    author: "Manohar Croke",
    category: "psychology",
    cover: "https://m.media-amazon.com/images/I/61ZY4rQaS6L._AC_UY218_.jpg",
    rating: 4.8,
    pages: 200,
    content: "<h3>Part One: Experiences in a Concentration Camp</h3><p>This book does not claim to be an account of facts and events but of personal experiences...</p>",
  },

    {
    id: 6,
    title: "Money Master The Game",
    author: "Tony Robbins",
    category: "finance",
    cover: "https://images-eu.ssl-images-amazon.com/images/I/71vgcI4foNL._AC_UL165_SR165,165_.jpg",
    rating: 4.7,
    pages: 256,
    content: "<h3>Chapter 1: No One's Crazy</h3><p>People do some crazy things with money. But no one is crazy...</p>",
  },
  {
    id: 7,
    title: "Success Secrets of Amazon",
    author: "Steve Anderson",
    category: "finance",
    cover: "https://m.media-amazon.com/images/I/81NDdnVUVkL._AC_UL320_.jpg",
    rating: 4.6,
    pages: 207,
    content: "<h3>Chapter 1: The Rich Don't Work for Money</h3><p>The poor and the middle class work for money. The rich have money work for them...</p>",
  },
  {
    id: 8,
    title: "The Millionaire Fastlane",
    author: "MJ DeMarco",
    category: "finance",
    cover: "https://m.media-amazon.com/images/I/41zc2B3TXhL._SY445_SX342_.jpg",
    rating: 4.6,
    pages: 336,
    content: "<h3>Chapter 1: The Road to Wealth</h3><p>Wealth is not a road, but a roadmap...</p>",
  },
  {
    id: 9,
    title: "Your Money or Your Life",
    author: "Vicki Robin",
    category: "finance",
    cover: "https://m.media-amazon.com/images/I/41jNuhEdL8L._SY445_SX342_.jpg",
    rating: 4.6,
    pages: 368,
    content: "<h3>Chapter 1: The Money Trap</h3><p>Money is something we trade our life energy for...</p>",
  },
  {
    id: 10,
    title: "The Intelligent Investor",
    author: "Benzamin Graham, Json Zweig",
    category: "finance",
    cover: "https://m.media-amazon.com/images/I/71vllLbpsdL._AC_UL320_.jpg",
    rating: 4.5,
    pages: 258,
    content: "<h3>Chapter 1: Meet the Millionaire Next Door</h3><p>Most people have it all wrong about wealth in America...</p>",
  },

  {
    id: 11,
    title: "The 4-Hour Body",
    author: "Timothy Ferriss",
    category: "health",
    cover: "https://m.media-amazon.com/images/I/718yDjorBpL._SY425_.jpg",
    rating: 4.3,
    pages: 592,
    content: "<h3>Chapter 1: The Minimum Effective Dose</h3><p>Forget about the marathon. Focus on the 100-meter dash...</p>",
  },
  {
    id: 12,
    title: "Your Own Body",
    author: "Dr Shiv Sarin",
    category: "health",
    cover: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ4ygendAOFiYb5Ly5n6arY0EXM31UG2lKcoJhOuS6-I2i63B1ar8rdChlq7c_WdmLLT-XbAHF7hgGiseAbMy2loWGa7z_qUjhVjFaGXR_BTq8-DhTbLfDo",
    rating: 4.8,
    pages: 368,
    content: "<h3>Chapter 1: To Sleep...</h3><p>Sleep is the single most effective thing we can do to reset our brain and body health each day...</p>",
  },
  {
    id: 13,
    title: "The Health Cocktail",
    author: "Dr. Deepika Sharma ",
    category: "health",
    cover: "https://m.media-amazon.com/images/I/51Qn0u7GlVL._AC_SF480,480_.jpg",
    rating: 4.6,
    pages: 296,
    content: "<h3>Chapter 1: The Epidemic</h3><p>Obesity is a hormonal, not a caloric imbalance...</p>",
  },
  {
    id: 14,
    title: "Breath",
    author: "James Nestor",
    category: "health",
    cover: "https://m.media-amazon.com/images/I/41VkkGS2bhL._SY445_SX342_.jpg",
    rating: 4.7,
    pages: 304,
    content: "<h3>Chapter 1: The Experiment</h3><p>No matter what you eat, how much you exercise, how skinny or young or wise you are...</p>",
  },
  {
    id: 15,
    title: "The Complete Human Body",
    author: "Alice Roberts",
    category: "health",
    cover: "https://m.media-amazon.com/images/I/51xiooX8y4L._SX342_SY445_.jpg",
    rating: 4.8,
    pages: 528,
    content: "<h3>Chapter 1: The Human Body</h3><p>The human body is a complex biological system...</p>",
  },

  
  {
    id: 16,
    title: "Buisness Today - 27 December",
    author: "by Businss Today Editorial Team",
    category: "business",
    cover: "https://m.media-amazon.com/images/I/81RdvgWrhVL._AC_UL320_.jpg",
    rating: 4.6,
    pages: 320,
    content: "<h3>Chapter 1: Good is the Enemy of Great</h3><p>That is one of the key reasons why we have so little that becomes great...</p>",
  },
  {
    id: 17,
    title: "Think Like Amazon",
    author: "John Rossman",
    category: "business",
    cover: "https://m.media-amazon.com/images/I/81LKndevdSL._AC_UL320_.jpg",
    rating: 4.5,
    pages: 336,
    content: "<h3>Chapter 1: Start</h3><p>The Lean Startup method is not about cost, it is about speed...</p>",
  },
  {
    id: 18,
    title: "The Bezos Letters",
    author: "Steve Anderson, karen Anderson",
    category: "business",
    cover: "https://m.media-amazon.com/images/I/81aICLwQ+fL._AC_UL320_.jpg",
    rating: 4.6,
    pages: 224,
    content: "<h3>Chapter 1: The Challenge of the Future</h3><p>What important truth do very few people agree with you on?...</p>",
  },
  {
    id: 19,
    title: "Business kohinoor : Ratan Tata",
    author: "B C Pandey",
    category: "business",
    cover: "https://m.media-amazon.com/images/I/61JLyn1PmnL._AC_UL320_.jpg",
    rating: 4.7,
    pages: 304,
    content: "<h3>Chapter 1: From Communist to Venture Capitalist</h3><p>There are no shortcuts to knowledge...</p>",
  },
  {
    id: 20,
    title: "The $100 Startup",
    author: "Chris Guillebeau",
    category: "business",
    cover: "https://m.media-amazon.com/images/I/41bRyTVDXqL._SY445_SX342_.jpg",
    rating: 4.4,
    pages: 304,
    content: "<h3>Chapter 1: Renaissance</h3><p>You don't need an MBA, a business plan, or even employees to be successful...</p>",
  },

  {
    id: 21,
    title: "To Good To Be true",
    author: "Prajakta Koli",
    category: "fiction",
    cover: "https://m.media-amazon.com/images/I/81pGO40uexL._AC_UL320_.jpg",
    rating: 4.8,
    pages: 281,
    content: "<h3>Chapter 1</h3><p>When he was nearly thirteen, my brother Jem got his arm badly broken at the elbow...</p>",
  },
  {
    id: 22,
    title: "Yellowface",
    author: "Rebecca F. Kaung",
    category: "fiction",
    cover: "https://m.media-amazon.com/images/I/61GKZcxOP7L._AC._SR360,460.jpg",
    rating: 4.7,
    pages: 328,
    content: "<h3>Chapter 1</h3><p>It was a bright cold day in April, and the clocks were striking thirteen...</p>",
  },
  {
    id: 23,
    title: "Jonathan Livingston Seagull: A Story",
    author: "Richrad Bach",
    category: "fiction",
    cover: "https://m.media-amazon.com/images/I/81uWX5+A1rL._SY385_.jpg",
    rating: 4.5,
    pages: 180,
    content: "<h3>Chapter 1</h3><p>In my younger and more vulnerable years my father gave me some advice...</p>",
  },
  {
    id: 24,
    title: "The Girl In Room 105",
    author: "Chetan Bhagat",
    category: "fiction",
    cover: "https://m.media-amazon.com/images/I/51J+KYDiEYL._AC._SR360,460.jpg",
    rating: 4.6,
    pages: 279,
    content: "<h3>Chapter 1</h3><p>It is a truth universally acknowledged, that a single man in possession of a good fortune...</p>",
  },
  {
    id: 25,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    category: "fiction",
    cover: "https://m.media-amazon.com/images/I/712cDO7d73L._SY425_.jpg",
    rating: 4.7,
    pages: 310,
    content: "<h3>Chapter 1: An Unexpected Party</h3><p>In a hole in the ground there lived a hobbit...</p>",
  },

  {
    id: 26,
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    category: "self-help",
    cover: "https://m.media-amazon.com/images/I/51pq8v0EbgL._AC_UY218_.jpg",
    rating: 4.7,
    pages: 381,
    content: "<h3>Chapter 1: Inside-Out</h3><p>The way we see the problem is the problem...</p>",
  },
  {
    id: 27,
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    category: "self-help",
    cover: "https://m.media-amazon.com/images/I/41OksZQYt+L._SY445_SX342_.jpg",
    rating: 4.7,
    pages: 288,
    content: "<h3>Chapter 1: Fundamental Techniques in Handling People</h3><p>If you want to gather honey, don't kick over the beehive...</p>",
  },
  {
    id: 28,
    title: "Deep Work",
    author: "Cal Newport",
    category: "self-help",
    cover: "https://m.media-amazon.com/images/I/41G4-FBs1YS._SY445_SX342_.jpg",
    rating: 4.6,
    pages: 304,
    content: "<h3>Chapter 1: Deep Work is Valuable</h3><p>The ability to perform deep work is becoming increasingly rare...</p>",
  },
  {
    id: 29,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    category: "self-help",
    cover: "https://m.media-amazon.com/images/I/416T7uchqcL._SY445_SX342_.jpg",
    rating: 4.6,
    pages: 224,
    content: "<h3>Chapter 1: Don't Try</h3><p>The key to a good life is not giving a fuck about more...</p>",
  },
  {
    id: 30,
    title: "Mindset: The New Psychology of Success",
    author: "Carol S. Dweck",
    category: "self-help",
    cover: "https://m.media-amazon.com/images/I/41KDq3tcN5L._SY445_SX342_.jpg",
    rating: 4.6,
    pages: 320,
    content: "<h3>Chapter 1: The Mindsets</h3><p>For twenty years, my research has shown that the view you adopt for yourself...</p>",
  },

  {
    id: 31,
    title: "Clean Code",
    author: "Robert C. Martin",
    category: "technology",
    cover: "https://m.media-amazon.com/images/I/41bOkXnNBjL._SY445_SX342_.jpg",
    rating: 4.7,
    pages: 464,
    content: "<h3>Chapter 1: Clean Code</h3><p>There are two things about code that matter. First, it needs to work...</p>",
  },
  {
    id: 32,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    category: "technology",
    cover: "https://m.media-amazon.com/images/I/41a1DYaecZL._SX342_SY445_.jpg",
    rating: 4.8,
    pages: 352,
    content: "<h3>Chapter 1: A Pragmatic Philosophy</h3><p>As a programmer, you are part listener, part advisor, part interpreter...</p>",
  },
  {
    id: 33,
    title: "Artificial Technology Intelligence",
    author: "Peter A. Maxwell",
    category: "technology",
    cover: "https://m.media-amazon.com/images/I/91ry2ncAzWL.jpg",
    rating: 4.9,
    pages: 600,
    content: "<h3>Chapter 1: Reliable, Scalable, and Maintainable Applications</h3><p>Many applications today are data-intensive...</p>",
  },
  {
    id: 34,
    title: "Chaos",
    author: "James Gleick",
    category: "technology",
    cover: "https://m.media-amazon.com/images/I/91RCspPB-PL._AC._SR360,460.jpg",
    rating: 4.6,
    pages: 322,
    content: "<h3>Chapter 1: The Tar Pit</h3><p>Programming is fun because it gratifies creative longings built deep within us...</p>",
  },
  {
    id: 35,
    title: "CareerCup Cracking The Pm Interview",
    author: "Gayle Laackman Mackdwell",
    category: "technology",
    cover: "https://m.media-amazon.com/images/I/61lpVd2HzXL._SY425_.jpg",
    rating: 4.7,
    pages: 960,
    content: "<h3>Chapter 1: Welcome to Software Construction</h3><p>Software construction is the central activity in software development...</p>",
  }
];